USE [master]
GO

DROP DATABASE IF EXISTS LoopTran;
DROP DATABASE IF EXISTS OneTran;

/****** Object:  Database [LoopTran]    Script Date: 2/9/2017 2:32:59 PM ******/
CREATE DATABASE [LoopTran]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoopTran', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LoopTran.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'LoopTran_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LoopTran_log.ldf' , SIZE = 1048576KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

ALTER DATABASE [LoopTran] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoopTran].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoopTran] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoopTran] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoopTran] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoopTran] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoopTran] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoopTran] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LoopTran] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoopTran] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoopTran] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoopTran] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoopTran] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoopTran] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoopTran] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoopTran] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoopTran] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LoopTran] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoopTran] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoopTran] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoopTran] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoopTran] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoopTran] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LoopTran] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoopTran] SET RECOVERY FULL 
GO

ALTER DATABASE [LoopTran] SET  MULTI_USER 
GO

ALTER DATABASE [LoopTran] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoopTran] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LoopTran] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LoopTran] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LoopTran] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LoopTran] SET QUERY_STORE = OFF
GO

USE [LoopTran]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LoopTran] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [OneTran]    Script Date: 2/9/2017 2:32:59 PM ******/
CREATE DATABASE [OneTran]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OneTran', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\OneTran.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'OneTran_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\OneTran_log.ldf' , SIZE = 1048576KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

ALTER DATABASE [OneTran] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OneTran].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OneTran] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OneTran] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OneTran] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OneTran] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OneTran] SET ARITHABORT OFF 
GO

ALTER DATABASE [OneTran] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OneTran] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OneTran] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OneTran] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OneTran] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OneTran] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OneTran] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OneTran] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OneTran] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OneTran] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OneTran] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OneTran] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OneTran] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OneTran] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OneTran] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OneTran] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OneTran] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OneTran] SET RECOVERY FULL 
GO

ALTER DATABASE [OneTran] SET  MULTI_USER 
GO

ALTER DATABASE [OneTran] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OneTran] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OneTran] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OneTran] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OneTran] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OneTran] SET QUERY_STORE = OFF
GO

USE [OneTran]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OneTran] SET  READ_WRITE 
GO

USE LoopTran
GO

SET NOCOUNT ON;
-- Create an populate a table in each database to use in the update loops
 
CREATE TABLE LoopTable
(runnumber INT
,rundate DATETIME
,vartext VARCHAR(10)
,chartext CHAR(10))
 
USE OneTran
GO
 
CREATE TABLE OneTable
(runnumber INT
,rundate DATETIME
,vartext VARCHAR(10)
,chartext CHAR(10))
 
USE LoopTran
GO
 
INSERT INTO LoopTable
VALUES
(1
,GETDATE()
,REPLICATE('a',10)
,REPLICATE('b',10))
GO 100000
 
USE OneTran
GO
 
INSERT INTO OneTable
VALUES
(1
,GETDATE()
,REPLICATE('a',10)
,REPLICATE('b',10))
GO 100000



