USE [master]
GO

IF DB_ID('BigLog') IS NOT NULL
BEGIN

	DROP DATABASE BigLog;

END

/****** Object:  Database [BigLog]    Script Date: 2/6/2017 4:36:57 PM ******/
CREATE DATABASE [BigLog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BigLog', 
	FILENAME = N'F:\DATA\BigLog.mdf' , 
	SIZE = 1024MB , 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BigLog_log', 
	FILENAME = N'F:\Log\BigLog_log.ldf' , 
	SIZE = 8192MB , 
	MAXSIZE = 2048GB , 
	FILEGROWTH = 1024MB )
GO

ALTER DATABASE [BigLog] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BigLog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BigLog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BigLog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BigLog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BigLog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BigLog] SET ARITHABORT OFF 
GO

ALTER DATABASE [BigLog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BigLog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BigLog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BigLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BigLog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BigLog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BigLog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BigLog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BigLog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BigLog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BigLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BigLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BigLog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BigLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BigLog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BigLog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BigLog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BigLog] SET RECOVERY FULL 
GO

ALTER DATABASE [BigLog] SET  MULTI_USER 
GO

ALTER DATABASE [BigLog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BigLog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BigLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BigLog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BigLog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BigLog] SET QUERY_STORE = OFF
GO

USE [BigLog]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BigLog] SET  READ_WRITE 
GO

BACKUP DATABASE BigLog TO DISK = 'C:\Backup\BigLog_FULL.bak' WITH COMPRESSION, STATS = 5;

EXEC sp_cycle_errorlog;