USE [master]
GO
IF DB_ID('SmallLog') IS NOT NULL
BEGIN

	DROP DATABASE SmallLog;

END


/****** Object:  Database [SmallLog]    Script Date: 2/6/2017 4:48:50 PM ******/
CREATE DATABASE [SmallLog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmallLog', 
	FILENAME = N'F:\DATA\SmallLog.mdf' , 
	SIZE = 1024MB , 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmallLog_log', 
	FILENAME = N'F:\Log\SmallLog_log.ldf' , 
	SIZE = 8192KB , 
	MAXSIZE = 2048GB , 
	FILEGROWTH = 1024KB)
GO

ALTER DATABASE [SmallLog] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmallLog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SmallLog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmallLog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmallLog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmallLog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmallLog] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmallLog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SmallLog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmallLog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmallLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmallLog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmallLog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmallLog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmallLog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmallLog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmallLog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmallLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmallLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmallLog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmallLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmallLog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmallLog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmallLog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmallLog] SET RECOVERY FULL 
GO

ALTER DATABASE [SmallLog] SET  MULTI_USER 
GO

ALTER DATABASE [SmallLog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmallLog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmallLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmallLog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SmallLog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SmallLog] SET QUERY_STORE = OFF
GO

USE [SmallLog]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SmallLog] SET  READ_WRITE 
GO

BACKUP DATABASE SmallLog TO DISK = 'C:\Backup\SmallLog_FULL.bak' WITH COMPRESSION, STATS = 5;

EXEC sp_cycle_errorlog;
